repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: dotnet format --verify-no-changes
        language: system
        types: [cs]
      - id: dotnet-test
        name: dotnet test
        entry: dotnet test DayByDay.sln --no-build --verbosity normal
        language: system
        pass_filenames: false
